import streamlit as st

st.title("Chromatix")

st.markdown(
    "There are 3 propogation methods:\n"
    + "1. transform: Uses Fresnel transform propagation\n"
    + "2. transfer: Uses Fresnel transfer propagation\n"
    + "3. exact: Uses exact transfer propagation with no Fresnel approximation\n\n"
    + "We start with a light field generated by a point source or a plane wave."
)
